authentication/urls.py
from django.urls import path
from authentication import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("user_register", views.register, name="register"),
    path("", views.user_login, name="user_login"),
    path("sair/", views.sair, name="sair"),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
        name="password_reset",
    ),
    path(
        "reset_password/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset_password/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset_password/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(
        "minhas_os/",
        views.minhas_os,
        name="minhas_os",
    ),
    path("atraso/<int:ordem_id>", views.atraso, name="atraso"),
    path("os_detail/<int:ordem_id>", views.os_detail, name="os_detail"),
    path("os_detail2/<int:ordem_id>", views.os_detail2, name="os_detail2"),
    path("os_detail3/<int:ordem_id>", views.os_detail3, name="os_detail3"),
    path("a_caminho/<int:ordem_id>", views.a_caminho, name="a_caminho"),
    path("no_local/<int:ordem_id>", views.no_local, name="no_local"),
    path("finalizar_os/<int:ordem_id>", views.finalizar_os, name="finalizar_os"),
    path("os_finalizadas/", views.os_finalizadas, name="os_finalizadas"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("tela_user/", views.tela_user, name="tela_user"),
    path("tela_busca/", views.tela_busca, name="tela_busca"),
    path(
        "tela_busca_resultado/", views.tela_busca_resultado, name="tela_busca_resultado"
    ),
    path("reagendar/<int:ordem_id>", views.reagendar, name="reagendar"),
    path("ocorrencias/<int:ordem_id>", views.ocorrencias, name="ocorrencias"),
    path("aceite/", views.aceite, name="aceite"),
    path("aceitar_ordem/<int:ordem_id>", views.aceitar_ordem, name="aceitar_ordem"),
    path("recusar_ordem/<int:ordem_id>", views.recusar_ordem, name="recusar_ordem"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("main/", include("main.urls")),
    path("staff/", include("staff.urls")),
    path("gerente/", include("gerente.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator
from .constants import STATE_CHOICES
from django.core.files.storage import default_storage


class Endereco(models.Model):
    cep = models.CharField(max_length=10)
    rua = models.CharField(max_length=30, validators=[MinLengthValidator(3)])
    bairro = models.CharField(max_length=20, validators=[MinLengthValidator(3)])
    cidade = models.CharField(max_length=20, validators=[MinLengthValidator(3)])
    estado = models.CharField(max_length=2, choices=STATE_CHOICES)
    numero = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    complemento = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.rua}, {self.numero}, {self.complemento}, {self.bairro}, {self.cidade}, {self.estado}, CEP: {self.cep}"


class CustomUser(AbstractUser):
    telefone = models.CharField(max_length=15, null=False)
    endereco = models.ForeignKey(
        Endereco, on_delete=models.CASCADE, null=True, default=None
    )
    foto = models.ImageField(upload_to="img/perfil_user/", null=True, blank=True)
    email = models.EmailField(unique=True)

    # Função que gera um nome pro arquivo de imagem
    def cliente_profile_filename(instance, filename):
        ext = filename.split(".")[-1]
        return f"{instance.first_name}_{instance.last_name}_profile.{ext}"

    def save(self, *args, **kwargs):
        if self.pk:  # Verifique se o usuário já existe no banco de dados
            try:
                # Obtém a instância atual do usuário no banco de dados
                old_user = CustomUser.objects.get(pk=self.pk)
                if old_user.foto and self.foto != old_user.foto:
                    # Se a instância atual tiver uma foto diferente da anterior
                    # exclua a foto anterior
                    default_storage.delete(old_user.foto.name)
            except CustomUser.DoesNotExist:
                pass

        # Chama a função que define o caminho da nova imagem
        if self.foto:
            self.foto.name = self.cliente_profile_filename(self.foto.name)

        super(CustomUser, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Endereco
import re
from django.contrib.auth.forms import AuthenticationForm


class CustomUserForm(UserCreationForm):
    GROUP_CHOICES = [
        ("Técnico", "Técnico")
    ]

    group = forms.ChoiceField(choices=GROUP_CHOICES)

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "telefone",
            "email",
        )

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

        self.fields["first_name"].widget.attrs["placeholder"] = "Nome"
        self.fields["last_name"].widget.attrs["placeholder"] = "Sobrenome"
        self.fields["telefone"].widget.attrs["placeholder"] = "Telefone"
        self.fields["email"].widget.attrs["placeholder"] = "Email"
        self.fields["password1"].widget.attrs["placeholder"] = "Senha"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirmação de Senha"
        self.fields["username"].widget.attrs["placeholder"] = "Usuário"
        

class EnderecoForm(forms.ModelForm):
    cep = forms.CharField(max_length=9, required=True)

    def clean_cep(self):
        cep = self.cleaned_data["cep"]
        if not re.match(r"^\d{5}-\d{3}$", cep):
            raise forms.ValidationError("CEP deve estar no formato XXXXX-XXX")
        return cep

    class Meta:
        model = Endereco
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(EnderecoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

        self.fields["cep"].widget.attrs["placeholder"] = "CEP"
        self.fields["bairro"].widget.attrs["placeholder"] = "Bairro"
        self.fields["rua"].widget.attrs["placeholder"] = "Rua"
        self.fields["cidade"].widget.attrs["placeholder"] = "Cidade"
        self.fields["estado"].widget.attrs["placeholder"] = "Estado"
        self.fields["numero"].widget.attrs["placeholder"] = "Numero"
        self.fields["complemento"].widget.attrs["placeholder"] = "Complemento"
        

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "Usuário"
        self.fields["password"].widget.attrs["class"] = "form-control"
        self.fields["password"].widget.attrs["placeholder"] = "Senha"


class TelaUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["telefone", "email", "first_name", "last_name", "foto"]

    def __init__(self, *args, **kwargs):
        super(TelaUserForm, self).__init__(*args, **kwargs)

        # Adicione a classe 'form-control' a todos os campos do formulário
        for field_name, field in self.fields.items():
            if "class" in field.widget.attrs:
                field.widget.attrs["class"] += " form-control"
            else:
                field.widget.attrs["class"] = "form-control"

authentication/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from .forms import CustomUserForm, EnderecoForm, CustomAuthenticationForm
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.messages import constants


def register(request):
    if request.method == "POST":
        form = CustomUserForm(request.POST)
        endereco_form = EnderecoForm(request.POST)
        if form.is_valid() and endereco_form.is_valid():
            user = form.save(commit=False)
            endereco = endereco_form.save()
            user.endereco = endereco
            user.save()
            group_name = form.cleaned_data["group"]
            if group_name == "Staff":
                group = Group.objects.get(name="Staff")
            elif group_name == "Técnico":
                group = Group.objects.get(name="Técnico")
            elif group_name == "Gerente":
                group = Group.objects.get(name="Gerente")
            user.groups.add(group)
            login(request, user)
            if user.groups.filter(name="Técnico").exists():
                return redirect("dashboard")  # Redireciona para a página de Técnico
            elif user.groups.filter(name="Staff").exists():
                return redirect("staff")  # Redireciona para a página de Staff
            elif user.groups.filter(name="Gerente").exists():
                return redirect("gerente")  # Redireciona para a página de Gerente

    else:
        form = CustomUserForm()
        endereco_form = EnderecoForm()
    return render(
        request, "register.html", {"form": form, "endereco_form": endereco_form}
    )


def user_login(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.groups.filter(name="Técnico").exists():
                    return redirect("dashboard")  # Redireciona para a página de Técnico
                elif user.groups.filter(name="Staff").exists():
                    return redirect("staff")
                elif user.groups.filter(name="Gerente").exists():
                    return redirect("gerente")  # Redireciona para a página de Staff
        else:
            messages.add_message(
                request, constants.ERROR, "Senha ou usuário incorretos"
            )
            return redirect("user_login")
    else:
        form = CustomAuthenticationForm()
    return render(request, "user_login.html", {"form": form})


def sair(request):
    logout(request)
    return redirect("user_login")

authentication/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% block styles %} {% endblock %}
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

authentication/templates/register.html
{%load static%}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="J.M.Campos">
    
    <meta name="generator" content="DGBZ">
    <title>App Maminfo</title>
    <link rel="canonical" href="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/app_mamminfo.css' %}" rel="stylesheet">
    <!-- Adicione o jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Adicione a biblioteca jQuery Mask Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

  </head>

  <body>
    <main>
      <section id="login_scr" class="bg02">
        <div class="container">
          <h1 class="font-bold">Maminfo</h1>
          
          <form id="form_cadastro" class="row" method="post">
            {% csrf_token %}
            
                      {% if form.errors %}
                      <div  class="alert alert-danger" role="alert">
                        <ul>
                          {% for field in form %}
                            {% for error in field.errors %}
                              <li>{{ field.label }}: {{ error }}</li>
                            {% endfor %}
                          {% endfor %}
                        </ul>
                      </div>
                    {% endif %}
                    
                    {% if endereco_form.errors %}
                      <div  class="alert alert-danger" role="alert">
                        <ul>
                          {% for field in endereco_form %}
                            {% for error in field.errors %}
                              <li>{{ field.label }}: {{ error }}</li>
                            {% endfor %}
                          {% endfor %}
                        </ul>
                      </div>
                    {% endif %}
           
            <div class="mb-3">
              {{ form.username }}
            </div>
            <div class="mb-3 col-6">
              {{ form.first_name }}
            </div>
            <div class="mb-3 col-6">
              {{ form.last_name }}
            </div>
            <div class="mb-3">
              {{ form.email }}
            </div>
            <div class="mb-3 col-6">
              {{ form.telefone }}
            </div>
            <div class="mb-3 col-6">
              {{ endereco_form.cep }}
            </div>
            <div class="mb-3" >
              {{ endereco_form.rua }}
            </div>
            <div class="mb-3" >
                {{ endereco_form.bairro }}
              </div>
            <div class="mb-3" >
                {{ endereco_form.cidade }}
              </div>
            <div class="mb-3">
                {{ endereco_form.estado}}
              </div>
            <div class="mb-3">
                {{ endereco_form.numero }}
              </div>
            <div class="mb-3">
                {{ endereco_form.complemento }}
              </div>
            <div class="mb-3">
              {{ form.password1 }}
            </div>
            <div class="mb-3">
              {{ form.password2 }}
            </div>
            <div class="mb-2">
              {{ form.group }}
            </div>
            <div class="mb-3">
              <button type="submit" class="btn bg01 text-light w-100 font-bold">Entrar</button>
          </div>
        </form>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var cepField = document.querySelector("[name='cep']");
                if (cepField) {
                    cepField.addEventListener("blur", function () {
                        var cep = this.value;
                        var url = `http://viacep.com.br/ws/${cep}/json/`;
        
                        fetch(url)
                            .then((response) => response.json())
                            .then((data) => {
                                document.querySelector("[name='rua']").value = data.logradouro;
                                document.querySelector("[name='bairro']").value = data.bairro;
                                document.querySelector("[name='cidade']").value = data.localidade;
                                document.querySelector("[name='estado']").value = data.uf;
                            });
                    });
                }
            });
        </script>
        
          <a href="{% url 'user_login' %}"class="w-100">Já tenho cadastro.</a>
        </div>
      </section>
      
    </main>

    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}">
     
      

    </script>
    <script>
      $(document).ready(function () {
        // Aplicar a máscara de CEP (#####-###) apenas ao campo CEP com o id 'id_cep'
        $('#id_cep').mask('00000-000');
      });
      $(document).ready(function () {
        // Aplicar a máscara de CEP (#####-###) apenas ao campo CEP com o id 'id_cep'
        $('#id_telefone').mask('(00) 00000-0000');
      });
    </script>

authentication/templates/reset_password.html
{%load static%}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="J.M.Campos">
    <meta name="generator" content="DGBZ">
    <title>App Maminfo</title>
    <link rel="canonical" href="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/app_mamminfo.css' %}" rel="stylesheet">
  </head>

  <body>

    <main>

      <section id="login_scr" class="bg04">
        <div class="container">
          <h1 class="font-bold">Maminfo</h1>
          <form id="form_login" method='post'>{% csrf_token %}
            <h5 class="text-center text-light">Esqueceu sua senha?</h5>
            <p class="text-center text-light lh-sm">Prencha seu e-mail abaixo para redefinir sua senha.</p>
            <div class="mb-3" id="email-field-container">
                {{ form.email }}
            </div>
            
            <div class="mb-3">
                <input type="submit" class="btn bg01 text-light w-100 font-bold" value="Enviar">
            </div>
          </form>

          
          <a href="{% url 'user_login' %}" class="w-100 mb-3 mt-4">Fazer login</a>
          <a href="{% url 'register' %}" class="w-100">Quero fazer meu cadastro</a>
     
        </div>
      </section>
      
    </main>


    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Selecionar o elemento de input dentro do container
            var emailFieldContainer = document.getElementById("email-field-container");
            var emailInput = emailFieldContainer.querySelector("input");
        
            // Verificar se o campo de e-mail foi encontrado
            if (emailInput) {
                emailInput.classList.add("form-control");
                emailInput.setAttribute("placeholder", "E-mail");
            }
        });
        </script>
  </body>

  </html>

authentication/templates/user_login.html
{%load static%}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="J.M.Campos">
    
    <meta name="generator" content="DGBZ">
    <title>App Maminfo</title>
    <link rel="canonical" href="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/app_mamminfo.css' %}" rel="stylesheet">
  </head>

  <body>

    <main>

      <section id="login_scr" class="bg01">
        <div class="container">
          <h1 class="font-bold">Maminfo</h1>
          <form id="form_login" method="post">
            {% if messages %}
            <br>
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
              </div>
            {% endfor %}
        
            {% endif %}
            {% csrf_token %}
            <div class="mb-2">
              {{form.username}}
            </div>
            <div class="mb-4">
              {{form.password}}
            </div>
            <div class="mb-2">
              <button type="submit" class="btn bg02 text-light w-100 font-bold">Entrar</button>
            </div>
          </form>
          <a href="{% url 'password_reset' %}" class="w-100 mb-3 mt-4">Esqueci minha senha.</a>
          <a href="{% url 'register' %}" class="w-100">Quero fazer meu cadastro.</a>
        </div>
      </section>
      
    </main>

    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

  </body>

  </html>