gerente/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("gerente/", views.gerente, name="gerente"),
    path("gerente_lista_os/", views.gerente_lista_os, name="gerente_lista_os"),
    path(
        "crud_gerente_os/<int:ordem_id>", views.crud_gerente_os, name="crud_gerente_os"
    ),
    path(
        "gerente_lista_clientes",
        views.gerente_lista_clientes,
        name="gerente_lista_clientes",
    ),
    path(
        "crud_gerente_clientes/<int:cliente_id>",
        views.crud_gerente_clientes,
        name="crud_gerente_clientes",
    ),
    path("gerente_lista_historico/", views.gerente_lista_historico, name="gerente_lista_historico"),
    path('deletar_os/<int:ordem_id>/', views.deletar_os, name='deletar_os'),
    path('deletar_cliente/<int:cliente_id>/', views.deletar_cliente, name='deletar_cliente'),
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(
        "minhas_os/",
        views.minhas_os,
        name="minhas_os",
    ),
    path("atraso/<int:ordem_id>", views.atraso, name="atraso"),
    path("os_detail/<int:ordem_id>", views.os_detail, name="os_detail"),
    path("os_detail2/<int:ordem_id>", views.os_detail2, name="os_detail2"),
    path("os_detail3/<int:ordem_id>", views.os_detail3, name="os_detail3"),
    path("a_caminho/<int:ordem_id>", views.a_caminho, name="a_caminho"),
    path("no_local/<int:ordem_id>", views.no_local, name="no_local"),
    path("finalizar_os/<int:ordem_id>", views.finalizar_os, name="finalizar_os"),
    path("os_finalizadas/", views.os_finalizadas, name="os_finalizadas"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("tela_user/", views.tela_user, name="tela_user"),
    path("tela_busca/", views.tela_busca, name="tela_busca"),
    path(
        "tela_busca_resultado/", views.tela_busca_resultado, name="tela_busca_resultado"
    ),
    path("reagendar/<int:ordem_id>", views.reagendar, name="reagendar"),
    path("ocorrencias/<int:ordem_id>", views.ocorrencias, name="ocorrencias"),
    path("aceite/", views.aceite, name="aceite"),
    path("aceitar_ordem/<int:ordem_id>", views.aceitar_ordem, name="aceitar_ordem"),
    path("recusar_ordem/<int:ordem_id>", views.recusar_ordem, name="recusar_ordem"),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("main/", include("main.urls")),
    path("staff/", include("staff.urls")),
    path("gerente/", include("gerente.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("staff/", views.staff, name="staff"),
    path("lista_os/", views.lista_os, name="lista_os"),
    path("lista_os_sem_tecnico/", views.lista_os_sem_tecnico, name="lista_os_sem_tecnico"),
    path("update_tecnico/<int:ordem_id>", views.update_tecnico, name="update_tecnico"),
    path("formulario_os/", views.formulario_os, name="formulario_os"),
    path("formulario_cliente/", views.formulario_cliente, name="formulario_cliente"),
    path("ordens_em_atraso/", views.ordens_em_atraso, name="ordens_em_atraso"),
    path("reagendar_staff/", views.reagendar_staff, name="reagendar_staff"),
    path(
        "update_reagendar/<int:ordem_id>",
        views.update_reagendar,
        name="update_reagendar",
    ),
]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator
from .constants import STATE_CHOICES
from django.core.files.storage import default_storage


class Endereco(models.Model):
    cep = models.CharField(max_length=10)
    rua = models.CharField(max_length=30, validators=[MinLengthValidator(3)])
    bairro = models.CharField(max_length=20, validators=[MinLengthValidator(3)])
    cidade = models.CharField(max_length=20, validators=[MinLengthValidator(3)])
    estado = models.CharField(max_length=2, choices=STATE_CHOICES)
    numero = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    complemento = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.rua}, {self.numero}, {self.complemento}, {self.bairro}, {self.cidade}, {self.estado}, CEP: {self.cep}"


class CustomUser(AbstractUser):
    telefone = models.CharField(max_length=15, null=False)
    endereco = models.ForeignKey(
        Endereco, on_delete=models.CASCADE, null=True, default=None
    )
    foto = models.ImageField(upload_to="img/perfil_user/", null=True, blank=True)
    email = models.EmailField(unique=True)

    # Função que gera um nome pro arquivo de imagem
    def cliente_profile_filename(instance, filename):
        ext = filename.split(".")[-1]
        return f"{instance.first_name}_{instance.last_name}_profile.{ext}"

    def save(self, *args, **kwargs):
        if self.pk:  # Verifique se o usuário já existe no banco de dados
            try:
                # Obtém a instância atual do usuário no banco de dados
                old_user = CustomUser.objects.get(pk=self.pk)
                if old_user.foto and self.foto != old_user.foto:
                    # Se a instância atual tiver uma foto diferente da anterior
                    # exclua a foto anterior
                    default_storage.delete(old_user.foto.name)
            except CustomUser.DoesNotExist:
                pass

        # Chama a função que define o caminho da nova imagem
        if self.foto:
            self.foto.name = self.cliente_profile_filename(self.foto.name)

        super(CustomUser, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

gerente/models.py
from django.db import models

# Create your models here.

staff/models.py
from django.db import models
from authentication.models import CustomUser, Endereco
from django.core.validators import MinLengthValidator
from authentication.constants import (
    STATUS_CHOICES,
    ACTIVITY_CHOICES,
    TECNICAL_CHOICES,
    ATRASO_CHOICES,
)


class Cliente(models.Model):
    nome = models.CharField(max_length=50, validators=[MinLengthValidator(3)])
    rg = models.CharField(max_length=12, validators=[MinLengthValidator(3)])
    telefone1 = models.CharField(max_length=15, validators=[MinLengthValidator(3)])
    telefone2 = models.CharField(max_length=15, validators=[MinLengthValidator(3)])

    def __str__(self):
        return self.nome


class OrdemDeServico(models.Model):
    ticket = models.CharField(max_length=200, unique=True)
    tecnico = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="ordens_técnico",
        null=True,
        default=None,
    )
    staff = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="ordens_staff"
    )
    descricao = models.TextField(max_length=600)
    previsao_chegada = models.DateTimeField(editable=True)
    previsao_execucao = models.DateTimeField(editable=True)
    material = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    equipamento = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    data_criacao = models.DateTimeField(auto_now_add=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    endereco = models.ForeignKey(Endereco, on_delete=models.CASCADE)
    contrato = models.CharField(max_length=700, null=True, blank=True)
    atividade = models.CharField(max_length=50, choices=ACTIVITY_CHOICES)
    status_tecnico = models.CharField(max_length=50, choices=TECNICAL_CHOICES)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="Aguardando"
    )
    atraso_em_minutos = models.CharField(max_length=50, choices=ATRASO_CHOICES)
    atraso_descricao = models.TextField(max_length=400)
    descricao_reagendamento = models.TextField(max_length=400)
    vezes_reagendada = models.IntegerField(default=0)
    aceite = models.BooleanField(default=False)

    def __str__(self):
        return f"Ordem de Serviço #{self.pk}"


class HistoricoOsFinalizada(models.Model):
    ordem_de_servico = models.ForeignKey(
        OrdemDeServico, on_delete=models.CASCADE, related_name="historico_os"
    )
    data_finalizada = models.DateTimeField(auto_now_add=True)
    nome_responsavel = models.CharField(max_length=30, null=False)
    rg_responsavel = models.CharField(max_length=12, null=False)
    observacoes = models.TextField(max_length=400)
    video = models.FileField(
        upload_to="videos/historico_os_finalizada/", null=True, blank=True
    )

    # def cliente_ticket_filename(instance, filename):
    #     ext = filename.split(".")[-1]
    #     return f"{instance.nome_responsavel}_{instance.ordem_de_servico.ticket}.{ext}"

    # def save(self, *args, **kwargs):
    #     # Chama a função que define o caminho da imagem
    #     if self.foto:
    #         self.foto.name = self.cliente_ticket_filename(self.foto.name)
    #     if self.video:
    #         self.video.name = self.cliente_ticket_filename(self.video.name)
    #     super(HistoricoOsFinalizada, self).save(*args, **kwargs)


class Ocorrencia(models.Model):
    ordem_de_servico = models.ForeignKey(
        OrdemDeServico, on_delete=models.CASCADE, related_name="ocorrencias"
    )
    titulo = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    descricao = models.TextField(max_length=600)
    data_criacao = models.DateTimeField(auto_now_add=True)
    foto = models.ImageField(upload_to="img/ocorrencias/", null=True, blank=True)
    video = models.FileField(upload_to="videos/ocorrencias/", null=True, blank=True)

    def ticket_tecnico_ocorrencia(instance, filename):
        ext = filename.split(".")[-1]
        return f"{instance.ordem_de_servico.ticket} - {instance.ordem_de_servico.tecnico.first_name}{instance.ordem_de_servico.tecnico.first_name}.{ext}"

    def save(self, *args, **kwargs):
        # Chama a função que define o caminho da imagem
        if self.foto:
            self.foto.name = self.ticket_tecnico_ocorrencia(self.foto.name)
        if self.video:
            self.video.name = self.ticket_tecnico_ocorrencia(self.video.name)
        super(Ocorrencia, self).save(*args, **kwargs)

    def __str__(self):
        return f"Ocorrência para Ordem de Serviço #{self.ordem_de_servico.pk}"


class FotoHistorico(models.Model):
    historico = models.ForeignKey(
        "HistoricoOsFinalizada", on_delete=models.CASCADE, related_name="fotos"
    )
    foto = models.ImageField(
        upload_to="img/historico_os_finalizada/", null=True, blank=True
    )

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Endereco
import re
from django.contrib.auth.forms import AuthenticationForm


class CustomUserForm(UserCreationForm):
    GROUP_CHOICES = [
        ("Técnico", "Técnico")
    ]

    group = forms.ChoiceField(choices=GROUP_CHOICES)

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "telefone",
            "email",
        )

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

        self.fields["first_name"].widget.attrs["placeholder"] = "Nome"
        self.fields["last_name"].widget.attrs["placeholder"] = "Sobrenome"
        self.fields["telefone"].widget.attrs["placeholder"] = "Telefone"
        self.fields["email"].widget.attrs["placeholder"] = "Email"
        self.fields["password1"].widget.attrs["placeholder"] = "Senha"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirmação de Senha"
        self.fields["username"].widget.attrs["placeholder"] = "Usuário"
        

class EnderecoForm(forms.ModelForm):
    cep = forms.CharField(max_length=9, required=True)

    def clean_cep(self):
        cep = self.cleaned_data["cep"]
        if not re.match(r"^\d{5}-\d{3}$", cep):
            raise forms.ValidationError("CEP deve estar no formato XXXXX-XXX")
        return cep

    class Meta:
        model = Endereco
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(EnderecoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

        self.fields["cep"].widget.attrs["placeholder"] = "CEP"
        self.fields["bairro"].widget.attrs["placeholder"] = "Bairro"
        self.fields["rua"].widget.attrs["placeholder"] = "Rua"
        self.fields["cidade"].widget.attrs["placeholder"] = "Cidade"
        self.fields["estado"].widget.attrs["placeholder"] = "Estado"
        self.fields["numero"].widget.attrs["placeholder"] = "Numero"
        self.fields["complemento"].widget.attrs["placeholder"] = "Complemento"
        

class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "Usuário"
        self.fields["password"].widget.attrs["class"] = "form-control"
        self.fields["password"].widget.attrs["placeholder"] = "Senha"


class TelaUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ["telefone", "email", "first_name", "last_name", "foto"]

    def __init__(self, *args, **kwargs):
        super(TelaUserForm, self).__init__(*args, **kwargs)

        # Adicione a classe 'form-control' a todos os campos do formulário
        for field_name, field in self.fields.items():
            if "class" in field.widget.attrs:
                field.widget.attrs["class"] += " form-control"
            else:
                field.widget.attrs["class"] = "form-control"

staff/templates/crud_gerente_os.html
{% extends "base_gerente.html" %}

{%load static%}

{% block style %}
.dentroform{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    
}

.inputs{
    margin-bottom: 10px;
}

#id_ticket,
#id_tecnico,
#id_descricao,
#id_previsao_chegada,
#id_previsao_execucao,
#id_material,
#id_equipamento,
#id_cliente,
#id_contrato,
#id_atividade,
#id_status {
  width: 350px;
  padding: .375rem .75rem;
  font-size: 1rem;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: .25rem;
  transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  box-shadow: none;
  outline: 0;
  align-self: center; /* Isso centralizará os campos verticalmente */
}
h2{
    color:orange;
  }
{% endblock %}
{% block rest %}
    <form method="post">
        {% csrf_token %}
        <div class="dentroform">
            <br>
            <h2>Atualizar OS </h2>
            <br>
            <div class="inputs">
            {{ form.ticket }}
            </div>
            <div class="inputs">
            {{ form.tecnico }}
            </div>
            <div class="inputs">
            {{ form.descricao }}
            </div>
            {{form2.previsao_chegada}}
            <div class="inputs">
            {{ form.previsao_chegada }}
            </div>
            <div class="inputs">
            {{ form.previsao_execucao }}
            </div>
            <div class="inputs">
            {{ form.material }}
            </div>
            <div class="inputs">
            {{ form.equipamento }}
            </div>
            <div class="inputs">
            {{ form.cliente }}
            </div>
            <div class="inputs">
            {{ form.contrato }}
            </div>
            <div class="inputs">
            {{ form.atividade }}
            </div>
            <div class="inputs">
            {{ form.status }}
            </div>     
            <input type="submit" value="Atualizar" class="btn btn-success">
           
            <div>
    </form>
    <br>
    <a href="{% url 'deletar_os' ordem.id %}" class="btn btn-danger">Deletar</a>    
    <br><br>
    {% endblock %}

staff/templates/formulario_cliente.html
{% extends "base_staff.html" %}
{% load static %}

{% block style %}
.dentroform {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.inputs {
    margin-bottom: 10px;
}

#id_nome,
#id_rg,
#id_telefone1,
#id_telefone2,
#id_cep,
#id_rua,
#id_bairro,
#id_cidade,
#id_estado,
#id_numero,
#id_complemento {
    width: 350px;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    box-shadow: none;
    outline: 0;
    align-self: center;
}
h2{
  color:orange;
}
{% endblock %}

{% block rest %}
<br>



<form method="post" action="{% url 'formulario_cliente' %}">
    {% csrf_token %}
    <div class="dentroform">
            {% if messages %}
            <br />
            {% for message in messages %}
            <div class="alert {{ message.tags }}">{{ message }}</div>
            {% endfor %}
            {% endif %}
            <h2>Dados do cliente</h2>
            <div class="inputs">
                {{ cliente_form.nome }}
            </div>
            <div class="inputs">
                {{ cliente_form.rg }}
            </div>
            <div class="inputs">
                {{ cliente_form.telefone1 }}
            </div>
            <div class="inputs">
                {{ cliente_form.telefone2 }}
            </div>

           
            

            <input type="submit" value="Cadastrar" class="btn btn-success" />
        </div>
    </form>
    <hr>
    <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br>
    {% block script %}
    <script>
        document.getElementById("id_cep").addEventListener("blur", function () {
            var cep = this.value;
            var url = `http://viacep.com.br/ws/${cep}/json/`;

            fetch(url)
                .then((response) => response.json())
                .then((data) => {
                    document.getElementById("id_rua").value = data.logradouro;
                    document.getElementById("id_bairro").value = data.bairro;
                    document.getElementById("id_cidade").value = data.localidade;
                    document.getElementById("id_estado").value = data.uf;
                });
        });
    </script>
    {% endblock %}

    {% block script2 %}
    <script>
        $(document).ready(function () {
            // Aplicar a máscara de CEP (#####-###) apenas ao campo CEP com o id 'id_cep'
            $("#id_cep").mask("00000-000");
        });
        $(document).ready(function () {
            $("#id_telefone1").mask("(00) 00000-0000");
        });
        $(document).ready(function () {
            $("#id_telefone2").mask("(00) 00000-0000");
        });
        $(document).ready(function () {
            $("#id_rg").mask("00.000.000-0");
        });
    </script>
    {% endblock %}
</div>
{% endblock %}

staff/templates/formulario_os.html
{% extends "base_staff.html" %}

{%load static%}

{% block style %}
.dentroform{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    
}

.inputs{
    margin-bottom: 10px;
}

#id_ticket,
#id_tecnico,
#id_descricao,
#id_previsao_chegada,
#id_previsao_execucao,
#id_material,
#id_equipamento,
#id_cliente,
#id_contrato,
#id_atividade,
#id_status {
  width: 350px;
  padding: .375rem .75rem;
  font-size: 1rem;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: .25rem;
  transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  box-shadow: none;
  outline: 0;
  align-self: center; /* Isso centralizará os campos verticalmente */
}
h2{
    color:orange;
  }
{% endblock %}
{% block rest %}



    <br>
    <form method="POST" action="{% url 'formulario_os' %}">
        {% csrf_token %}
        <div class="dentroform">
            {% if messages %}
            <br>
            {% for message in messages %}
                <div class="alert {{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
            {% endif %}
        <h2>Dados da OS </h2>
        <div class="inputs">
        {{ os_form.ticket }}
        </div>
        <div class="inputs">
        {{ os_form.descricao }}
        </div>
        <div class="inputs">
        {{ os_form.previsao_chegada }}
        </div>
        <div class="inputs">
        {{ os_form.previsao_execucao }}
        </div>
        <div class="inputs">
        {{ os_form.material }}
        </div>
        <div class="inputs">
        {{ os_form.equipamento }}
        </div>
        <div class="inputs">
        {{ os_form.cliente }}
        </div>
        <div class="inputs">
        {{ os_form.contrato }}
        </div>
        <div class="inputs">
        {{ os_form.atividade }}
        </div>
        <div class="inputs">
        {{ os_form.status }}
        </div>
        <h2>Endereço da OS </h2>
        <div class="inputs">
            {{ endereco_form.cep }}
        </div>
        <div class="inputs">
            {{ endereco_form.estado }}
        </div>
        <div class="inputs">
            {{ endereco_form.cidade }}
        </div>
        <div class="inputs">
            {{ endereco_form.bairro }}
        </div>
        <div class="inputs">
            {{ endereco_form.rua}}
        </div>
        <div class="inputs">
            {{ endereco_form.numero}}
        </div>
        <div class="inputs">
            {{ endereco_form.complemento }}
        </div>


        <input type="submit" value="Cadastrar" class="btn btn-success">
        <div>
        </form>
        <hr>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var cepField = document.querySelector("[name='cep']");
                if (cepField) {
                    cepField.addEventListener("blur", function () {
                        var cep = this.value;
                        var url = `http://viacep.com.br/ws/${cep}/json/`;
        
                        fetch(url)
                            .then((response) => response.json())
                            .then((data) => {
                                document.querySelector("[name='rua']").value = data.logradouro;
                                document.querySelector("[name='bairro']").value = data.bairro;
                                document.querySelector("[name='cidade']").value = data.localidade;
                                document.querySelector("[name='estado']").value = data.uf;
                            });
                    });
                }
            });
        </script>
        

{% endblock %}
{% block script2 %}
<script>
    $(document).ready(function () {
        // Aplicar a máscara de CEP (#####-###) apenas ao campo CEP com o id 'id_cep'
        $("#id_cep").mask("00000-000");
    });
    $(document).ready(function () {
        $("#id_telefone1").mask("(00) 00000-0000");
    });
    $(document).ready(function () {
        $("#id_telefone2").mask("(00) 00000-0000");
    });
    $(document).ready(function () {
        $("#id_rg").mask("00.000.000-0");
    });
</script>
{% endblock %}

staff/templates/update_reagendar.html
{% extends "base_staff.html" %}

{%load static%}

{% block style %}
.dentroform{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    
}

.inputs{
    margin-bottom: 10px;
}

#id_ticket,
#id_staff,
#id_tecnico,
#id_descricao,
#id_previsao_chegada,
#id_previsao_execucao,
#id_material,
#id_equipamento,
#id_cliente,
#id_contrato,
#id_atividade,
#id_status {
  width: 350px;
  padding: .375rem .75rem;
  font-size: 1rem;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: .25rem;
  transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  box-shadow: none;
  outline: 0;
  align-self: center; /* Isso centralizará os campos verticalmente */
}
h2{
    color:orange;
  }
{% endblock %}
{% block rest %}
    <form method="post">
        {% csrf_token %}
        <div class="dentroform">
            <br>
            <h2>Atualizar Previsão de chegada</h2>
            <br>
            <div class="inputs">
            {{ form.previsao_chegada }}
            </div>
            <div class="inputs">
            {{ form.previsao_execucao }}
            </div>
            <div class="inputs">
                {{ form.status }}
            </div>
            <div class="inputs">
                {{ form.tecnico }}
            </div>
            <br><br><br>
            
            
            <input type="submit" value="Atualizar" class="btn btn-success ">
            <div>
    </form>
    <br><br><br><br><br><br><br><br><br>     <br><br><br><br><br><br><br><br><br>           

   

    {% endblock %}

staff/templates/update_tecnico.html
{% extends "base_staff.html" %}

{%load static%}

{% block style %}
.dentroform{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    
}

.inputs{
    margin-bottom: 10px;
}


#id_tecnico {
  width: 300px;
  padding: .375rem .75rem;
  font-size: 1rem;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: .25rem;
  transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  box-shadow: none;
  outline: 0;
  align-self: center; /* Isso centralizará os campos verticalmente */
}
h2{
    color:orange;
  }
  h3{
    color:orange;
    font-size: 14px;
  }

  hr{
    color:orange;
  }
  p{
    color:orange;
    font-size: 14px;
    text-align: center;
  }
{% endblock %}
{% block rest %}



    <br>
    <form method="POST">
        {% csrf_token %}
        <div class="dentroform">
            {% if tecnicos_proximos %}
            <p>Essa OS tem como endereço: {{ ordem.endereco }}</p>
            <br>
            <h3>Os 10 técnicos mais próximos:</h3>
            <br>
            <ol>
                {% for tecnico, distancia in tecnicos_proximos %}
                    <li>{{ tecnico }} - Reside em {{tecnico.endereco.cidade}} bairro {{tecnico.endereco.bairro}} - Distância: {{ distancia|floatformat:"2" }} km</li>
                    <hr>
                {% endfor %}
            </ol>
        {% endif %}
            <h3>Escolha um técnico para concluir o cadastro:</h3>
            <div class="inputs">
                {{ form.as_p }}
            </div>
            <input type="submit" value="Cadastrar" class="btn btn-success">
        </div>
    </form>
    
   
    

    
  
    <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>
    <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>     <br>     
    <hr>

{% endblock %}